### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by james-lawrence** [vrischmann/go-metrics-influxdb#12]
this repo still being maintained?

**Comment by vrischmann** [comment]
If someone sends a PR I'll review/merge it, if there's a simple issue I can fix without spending too much time I'll do that too.

But as far as keeping up myself with new stuff from either go-metrics and/or InfluxDB, improving this package myself, no I don't do that.

The reason is simple: we stopped using both go-metrics and InfluxDB.

**Comment by allingeek** [comment]
Can I ask what you're using instead these days?

**Comment by vrischmann** [comment]
@allingeek Sure, we're using Prometheus. If you're unsure what to use I'd definitely recommend it, in my opinion the ecosystem around Prometheus is much better than InfluxDB. Or at least it was when we made the switch, I admit I didn't look recently.
